baseURL = "http://example.org/"
languageCode = "en-us"
title = "Urban Rigger"
theme = "blank"
publishDir = "docs"


[[menu.main]]
name               	= "Home"
titel               = "Home"
weight             	= -201
identifier         	= "home"
url                	= "/"


[[menu.main]]
name               	= "Projects"
titel               = "Projects"
weight             	= -201
identifier         	= "projects"
url                	= "/projects"

[[menu.main]]
name               	= "View container"
titel               = "View container"
weight             	= -101
identifier         	= "view"
url                	= "/view"


[[menu.main]]
name               	= "Sustainbility"
titel               = "Sustainbility"
weight             	= -101
identifier         	= "sustan"
url                	= "/sustan"

[[menu.main]]
name               	= "About us"
titel               = "About us"
weight             	= -101
identifier         	= "aboutus"
url                	= "/aboutus"

[[menu.main]]
name               	= "Contact"
titel               = "Contact"
weight             	= -101
identifier         	= "contact"
url                	= "/contact"

[[menu.main]]
name               	= "Students"
titel               = "Students"
weight             	= -101
identifier         	= "students"
url                	= "/students"